apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleg
  labels:
    app.kubernetes.io/name: pleg
spec:
  replicas: 66
  selector:
    matchLabels:
      app.kubernetes.io/name: pleg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pleg
    spec:
      containers:
        - name: pleg1
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
        - name: pleg2
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
        - name: pleg3
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
        - name: pleg4
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
        - name: pleg5
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
        - name: pleg6
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
        - name: pleg7
          image: centos:7
          command:
            - bash
          args:
            - -c
            - "while true; do echo 'Just hanging out foo'; sleep 5; done"
