apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-cloner
spec:
  selector:
    matchLabels:
      app: git-cloner
  replicas: 1
  template:
    metadata:
      labels:
        app: git-cloner
    spec:
      containers:
      - name: git-cloner
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/git-cloner:latest
